name: Garmin Scale Sync

on:
  schedule:
    - cron: '0 5 * * *' # Автозапуск каждое утро
  workflow_dispatch: # Кнопка для ручного запуска

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build SmartScaleConnect
        run: |
          go build -o smartscaleconnect main.go || go build -o smartscaleconnect ./cmd/smartscaleconnect/main.go || go build -o smartscaleconnect .

      - name: Run Sync
        env:
          GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
          GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
          XIAOMI_USERNAME: ${{ secrets.ZEPP_USERNAME }}
          XIAOMI_PASSWORD: ${{ secrets.ZEPP_PASSWORD }}
        run: |
          ./smartscaleconnect --from xiaomi $XIAOMI_USERNAME $XIAOMI_PASSWORD --to garmin $GARMIN_USERNAME $GARMIN_PASSWORD
