name: Garmin Scale Sync

on:
  schedule:
    - cron: '0 5 * * *' # Автозапуск каждое утро
  workflow_dispatch: # Кнопка для ручного запуска

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build SmartScaleConnect
        run: |
          go build -o smartscaleconnect .

      - name: Run Sync
        run: |
          ./smartscaleconnect -c config.yml
